# Identification du projet
sonar.projectKey=crudapp
sonar.projectName=CrudApp
sonar.projectVersion=1.0

# Sources et tests
sonar.sources=src
sonar.tests=src

# Inclusion des tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

# Exclusions
sonar.exclusions=**/node_modules/**

# Couverture de code (Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Serveur SonarQube
sonar.host.url=http://localhost:9001

# Authentification (token SonarQube)
sonar.login=sqp_4cd3643c50f066481be904d64721549fc3e016a5
